[package]
name = "centripetal"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["rlib", "cdylib"]

[[bin]]
name = "centripetal-desktop"
path = "src/main.rs"

[dependencies]
hephae = "0.7"

[dependencies.bevy]
version = "0.15"
default-features = false
features = [
    "android-game-activity",
    "android_shared_stdcxx",
    "multi_threaded",
    "bevy_core_pipeline",
    "bevy_winit",
]

[build-dependencies]
vcpkg = "0.2"
