max_width = 125
single_line_let_else_max_width = 100
single_line_if_else_max_width = 100
overflow_delimited_expr = true
force_multiline_blocks = false
newline_style = "Native"
trailing_semicolon = false
trailing_comma = "Vertical"
binop_separator = "Back"

imports_indent = "Block"
imports_layout = "Mixed"
imports_granularity = "Crate"
reorder_imports = true
group_imports = "StdExternalCrate"
reorder_modules = true

format_code_in_doc_comments = true
wrap_comments = true
comment_width = 100
